[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-url.com"  # バックエンドのURLは後で更新

[[plugins]]
  package = "@netlify/plugin-nextjs" 