services:
  app:
    build: .
    container_name: iot_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python main.py

  test:
    build: .
    container_name: iot_test
    volumes:
      - .:/app
    command: ["pytest", "--disable-warnings"]
