version: "3.8"

services:
  frontend:
    build:
      context: ./frontend  # フロントエンドの Dockerfile の場所
      dockerfile: Dockerfile
    container_name: iot_frontend
    ports:
      - "3000:3000"  # Next.js のポート
    volumes:
      - ./frontend:/app  # コード変更をリアルタイムで反映
      - /app/node_modules  # node_modules をホストと分離
    depends_on:
      app:
        condition: service_healthy  # Flask が準備完了後に起動
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iot_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - PYTHONUNBUFFERED=1
    command: [ "sh", "-c", "/app/venv/bin/python -m flask run --host=0.0.0.0 --port=5000" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s

