version: "3.8"

services:
  app:
    build:
      context: .
      target: base
    container_name: iot_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: ["python", "main.py"]
