name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python環境をセットアップ
        uses: actions/setup-python@v3
        with:
          # Lambdaのランタイムに合わせたPythonバージョンを指定する
          python-version: '3.13'

      - name: 依存関係をインストール
        run: |
          pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: ZIPファイルを作成
        run: cd lambda && zip -r ../lambda_function.zip .

      # AWSクレデンシャルの設定 (公式アクション)
      - name: AWS 認証の設定
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      # デプロイ
      - name: Lambda 関数をアップデート
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --zip-file fileb://lambda_function.zip

