name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python環境をセットアップ
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      - name: 依存関係をインストール
        run: |
          pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: ZIPファイルを作成
        run: cd lambda && zip -r ../lambda_function.zip .

      - name: AWS 認証の設定
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # GitHub Secrets に追加
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS Lambdaにデプロイ
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: my-lambda-function  # Lambda関数名を指定
          zip-file: lambda_function.zip
