name: Deploy AWS Lambda

on:
  push:
    branches:
      - main  # ✅ main ブランチにプッシュされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies (Lambda 用)
        run: pip install -r requirements-lambda.txt -t .

      - name: Zip application
        run: zip -r lambda_function.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: my-test-lambda
          zip-file: lambda_function.zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # AWSのリージョン（適宜変更）
