name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python環境をセットアップ
        uses: actions/setup-python@v3
        with:
          # Lambdaのランタイムに合わせたPythonバージョンを指定する
          python-version: '3.13'

      - name: 依存関係をインストール
        run: |
          pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: ZIPファイルを作成
        run: cd lambda && zip -r ../lambda_function.zip .

      # 環境変数の確認
      - name: 環境変数の確認 (Debug)
        run: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "ブランチ名=${GITHUB_REF#refs/heads/}"

      # OIDC トークンを取得
      - name: Get OIDC Token
        run: |
          curl -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r '.value' > token.jwt

      # IAM ロールを Assume できるかテスト
      - name: Assume AWS Role
        run: |
          aws sts assume-role-with-web-identity \
            --role-arn "arn:aws:iam::490004643576:role/github-actions-lambda-deploy" \
            --role-session-name "GitHubActionsSession" \
            --web-identity-token file://token.jwt \
            --duration-seconds 900
